### ISSUE TITLE
tooltip tip upgrade?

### ISSUE THREAD

**Issue by tborychowski** [perfect-things/ui#17]
```css
.triangle {
   clip-path: polygon(50% 0%, 0% 100%, 100% 100%);
}
```
