### ISSUE TITLE
add input invalid styling for `invalid` class

### ISSUE THREAD

**Issue by tborychowski** [perfect-things/ui#33]
add sth like this:

```css
input.invalid,
input.invalid:focus {
	border-color: var(--ui-color-danger);
	box-shadow: 0 0 0 1px var(--ui-color-danger);
}
```
